### ISSUE TITLE
Decide on Headless Blog CMS

### ISSUE THREAD

**Issue by knittingarch** [knittingarch/censorix#5]

**Comment by knittingarch** [comment]
In particular, it needs to allow customize theming and publishable content.
Nice to have: RSS, SEO

**Comment by knittingarch** [comment]
https://buttercms.com/rails-blog-engine/
https://dev.to/justalever/lets-build-with-ruby-on-rails---a-blog-with-comments-17lc
Ghost
Wordpress

**Comment by sneamonitakis** [comment]
https://ghost.org/features/

**Comment by knittingarch** [comment]
@sneamonitakis I've looked through these three and Ghost is standing out to me as the most easy to use from a content perspective, but I'd love your feedback on the theming. It sounded like you'd either had experience using Handlebars or were keen to learn it.  Is that right?  

Anyway, at $30/month, it seems worthwhile to at least download it and see what it's like.  It certainly looks tidier than WordPress.

**Comment by sneamonitakis** [comment]
@knittingarch Sounds like a plan!
